"""Layer 3: SQL output validator.

Validates SQL generated by the LLM before execution.
Whitelists SELECT-only, blocks system table access, dangerous functions, etc.
"""
from __future__ import annotations

import re
import logging

from app.guardrails.input_filter import GuardrailResult, Verdict

logger = logging.getLogger(__name__)

# ── Whitelisted statement types ─────────────────────────────────
# Only SELECT and EVALUATE (Power BI DAX) are allowed
_ALLOWED_PREFIXES = re.compile(
    r"^\s*(SELECT|EVALUATE|WITH)\b",
    re.IGNORECASE,
)

# ── Blocked DML/DDL statements ──────────────────────────────────
_BLOCKED_STATEMENTS = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|GRANT|REVOKE|"
    r"EXEC|EXECUTE|CALL|MERGE|REPLACE|UPSERT|COPY|SET\s+ROLE|"
    r"SET\s+SESSION|SHUTDOWN|KILL)\b",
    re.IGNORECASE,
)

# ── Blocked system tables/schemas ───────────────────────────────
_SYSTEM_TABLES = re.compile(
    r"\b(information_schema|pg_catalog|pg_stat|pg_class|pg_proc|pg_roles|"
    r"pg_shadow|pg_authid|pg_user|sys\.objects|sys\.tables|sys\.columns|"
    r"sysobjects|syscolumns|msdb|master\.\.|MASTER\.\.|"
    r"sqlite_master|sqlite_schema|mysql\.user|mysql\.db|"
    r"ALL_TABLES|ALL_TAB_COLUMNS|DBA_USERS|V\$SESSION)\b",
    re.IGNORECASE,
)

# ── Blocked dangerous functions ─────────────────────────────────
_DANGEROUS_FUNCTIONS = re.compile(
    r"\b(pg_read_file|pg_read_binary_file|pg_ls_dir|pg_stat_file|"
    r"lo_import|lo_export|dblink|copy_to|copy_from|"
    r"xp_cmdshell|sp_executesql|sp_configure|openrowset|opendatasource|"
    r"load_file|into\s+outfile|into\s+dumpfile|"
    r"UTL_FILE|UTL_HTTP|DBMS_PIPE|DBMS_SCHEDULER|"
    r"pg_sleep|sleep|benchmark|waitfor\s+delay|"
    r"current_setting|set_config)\b",
    re.IGNORECASE,
)

# ── Stacked queries (multiple statements) ───────────────────────
_STACKED_QUERIES = re.compile(
    r";\s*(SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|EXEC|SET|GRANT)\b",
    re.IGNORECASE,
)

# ── Comment injection ──────────────────────────────────────────
_COMMENT_INJECTION = re.compile(
    r"(--|/\*.*\*/|#)\s*(DROP|DELETE|INSERT|UPDATE|EXEC|ALTER)",
    re.IGNORECASE,
)

# ── Row limits for safety (prevent accidental full-table scans) ──
MAX_ROWS_SOFT = 10000  # Log a warning
MAX_ROWS_HARD = 50000  # Block


def validate_sql(sql: str, connector_type: str = "postgresql") -> GuardrailResult:
    """Validate LLM-generated SQL before execution.

    Args:
        sql: The SQL string to validate.
        connector_type: "postgresql", "cosmosdb", or "powerbi"

    Returns:
        GuardrailResult with verdict.
    """
    if not sql or not sql.strip():
        return GuardrailResult(
            verdict=Verdict.BLOCK,
            reason="Empty SQL query",
            layer="sql_validator",
        )

    cleaned = sql.strip()

    # 1. Must start with SELECT or EVALUATE
    is_cosmos = connector_type.lower() in ("cosmosdb", "cosmos db")
    is_pbi = connector_type.lower() in ("powerbi", "power bi")

    if not is_pbi and not _ALLOWED_PREFIXES.match(cleaned):
        return GuardrailResult(
            verdict=Verdict.BLOCK,
            reason=f"Only SELECT queries allowed, got: {cleaned[:50]}",
            layer="sql_validator",
        )

    # 2. Block DML/DDL statements
    if _BLOCKED_STATEMENTS.search(cleaned):
        match = _BLOCKED_STATEMENTS.search(cleaned)
        return GuardrailResult(
            verdict=Verdict.BLOCK,
            reason=f"Dangerous SQL statement detected: {match.group() if match else 'unknown'}",
            layer="sql_validator",
        )

    # 3. Block system table access
    if _SYSTEM_TABLES.search(cleaned):
        match = _SYSTEM_TABLES.search(cleaned)
        return GuardrailResult(
            verdict=Verdict.BLOCK,
            reason=f"System table access blocked: {match.group() if match else 'unknown'}",
            layer="sql_validator",
        )

    # 4. Block dangerous functions
    if _DANGEROUS_FUNCTIONS.search(cleaned):
        match = _DANGEROUS_FUNCTIONS.search(cleaned)
        return GuardrailResult(
            verdict=Verdict.BLOCK,
            reason=f"Dangerous SQL function blocked: {match.group() if match else 'unknown'}",
            layer="sql_validator",
        )

    # 5. Block stacked queries
    if _STACKED_QUERIES.search(cleaned):
        return GuardrailResult(
            verdict=Verdict.BLOCK,
            reason="Multiple SQL statements (stacked queries) detected",
            layer="sql_validator",
        )

    # 6. Block comment-based injection
    if _COMMENT_INJECTION.search(cleaned):
        return GuardrailResult(
            verdict=Verdict.BLOCK,
            reason="SQL comment injection detected",
            layer="sql_validator",
        )

    # 7. Check for missing LIMIT/TOP (flag, don't block)
    if not is_cosmos and not is_pbi:
        has_limit = re.search(r"\bLIMIT\s+\d+", cleaned, re.IGNORECASE)
        has_top = re.search(r"\bTOP\s+\d+", cleaned, re.IGNORECASE)
        has_group = re.search(r"\bGROUP\s+BY\b", cleaned, re.IGNORECASE)
        has_count = re.search(r"\bCOUNT\s*\(", cleaned, re.IGNORECASE)
        if not has_limit and not has_top and not has_group and not has_count:
            return GuardrailResult(
                verdict=Verdict.FLAG,
                reason="Query has no LIMIT, TOP, GROUP BY, or aggregate — may return large result",
                layer="sql_validator",
            )

    return GuardrailResult(verdict=Verdict.PASS, layer="sql_validator")
